name: Build MemeCoinsApp v4 (APK)

on:
  push:
    branches:
      - main
  workflow_dispatch:  # позволяет запускать вручную через вкладку Actions

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle cache
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./app/gradlew

      - name: Build APK (Debug)
        working-directory: app
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MemeCoinsApp-v4-debug
          path: app/build/outputs/apk/debug/*.apk
